### PR TITLE
Option to manage properties by table

### PR DESCRIPTION
**Pull request by ajostergaard**
Also changed all options to use 'expires' rather than expiry in some cases.

### CODE REVIEW

**Comment by notheotherben** [comment]
I like the idea, though I've got another approach which might work a bit better - let me know what you think about it and if you like it I can go about implementing it as an option (it will also ensure that we remain backwards compatible).

My solution is to use the current configuration to set the module's defaults, and then allow overriding of those using the `timestamp: ...` property. That way, we can maintain current behavior by specifying `timestamp: true` or override specific options by specifying `timestamp: { option1: value1 }` instead.

I've thrown together a quick example on feature/table-options if you'd like to take a look.

**Comment by ajostergaard** [comment]
I think the current behaviour is maintained using timestamp=true isn't it?

## 

AJ Ostergaard
Tapped by thumb on the move - please excuse my brevity.

**Comment by notheotherben** [comment]
That's correct, but in this way we have two major advantages.
1. We can change every configuration option on a per-table basis (as opposed to just enabling/disabling the different options).
2. We don't run the risk of option collisions with any other plugins (since all the options are contained within our `timestamp` property).

**Comment by ajostergaard** [comment]
Can't argue with that. :) Will take a look tomorrow... It's getting late here now. 

## 

AJ Ostergaard
Tapped by thumb on the move - please excuse my brevity.

**Comment by notheotherben** [comment]
I've merged feature/table-options which provides this functionality, will be closing this pull request.

**Pull request closed without merging**
