### PR TITLE
Expiration property

### PR DESCRIPTION
**Pull request by ajostergaard**
Added an expiration field property.

### CODE REVIEW

**Comment by notheotherben** [comment]
Hi ajostergaard,
Thanks for the feature, looks very cool and will be happy to merge it, would you mind just setting it to be disabled by default (default options `expiresProperty: false`) so that we can ensure changes are backwards compatible with current setups? (If you'd like, I can do so as well but I'd like to give you credit for it in the commit log).

**Comment by ajostergaard** [comment]
Will do... In a few hours. :)

## 

AJ Ostergaard - M: +971557582626
Tapped by thumb on the move - please excuse my brevity.

**Comment by ajostergaard** [comment]
Done.

PS: Not sure I want to take credit for such a messy bunch of commits. Never used GitHub for this before though so you live and learn. Hopefully! ;)

**Comment by ajostergaard** [comment]
I've actually got another feature queued up - I've added table level options each of the timestamp properties can be enabled/disabled and the expires function can be different per table. Also normalised so all config options use 'expires' rather than expires sometimes and expiry sometimes. Interested? If so, shall I merge the whole thing into my master so you can just pull once?

**Comment by notheotherben** [comment]
Let me merge this one quickly and then you can open another pull request, that way we can go through any issues with it and figure out whether it's backwards compatible (or if we need to bump the major version). Thanks for the work :+1:

**Pull request merged**
